# -*- coding: utf-8 -*-
"""Вычисление кратной точки.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11hjWWwLWaxbNaeoz6ElUgHiaRaMl5phg
"""

e=int(0)
d=int(0)
while(e*d*(1-e*e*e*e*d)==0):
    print("Помните, что существуют ограничения на e и d: e*d*(1-e^4*d)!=0")
    e = int(input("Введите параметр e: "))
    d = int(input("Введите параметр d: "))
    print("Параметры кривой Эдварса: "+ "e=" + str(e) + ", " + "d=" + str(d))
x=1
y=0
print("Введите координаты точки, которую вы хотите удвоить")
x=float(input("x="))
y=float(input("y="))
print("Искомая кратная точка на кривой Эдвардса с параметрами "+"e=" + str(e) + ", d="+ str(d) + ":")
print("P2" +"(" + str(float(2*x*y/(e+e*d*x*x*y*y))) +  "," + str(float((y*y-x*x)/(e-e*d*x*x*y*y))) + ")")